"""YOLO (Ultralytics) exporter — one .txt per image plus a data.yaml."""

from __future__ import annotations

import shutil
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import Annotation, Category, Image
from app.services import storage
from app.services.exporters.base import DatasetExporter, ExportRequest, coco_to_yolo


class YoloExporter(DatasetExporter):
    key = "yolo"
    display_name = "YOLO (Ultralytics)"
    description = "One .txt per image + data.yaml. Consumed by YOLO26 / ultralytics."

    def export(self, db: Session, request: ExportRequest) -> Path:
        root = request.out_dir
        root.mkdir(parents=True, exist_ok=True)

        categories = list(
            db.scalars(
                select(Category)
                .where(Category.project_id == request.project_id)
                .order_by(Category.id)
            ).all()
        )
        images = list(
            db.scalars(
                select(Image)
                .where(Image.project_id == request.project_id)
                .order_by(Image.id)
            ).all()
        )

        # YOLO class ids are 0-BASED positional indices into data.yaml's names
        # list — NOT database ids. Off-by-one here trains every object as the
        # wrong class, and nothing errors: you just get a model that confidently
        # calls cars "people".
        class_index = {c.id: i for i, c in enumerate(categories)}

        splits_seen: set[str] = set()

        for image in images:
            split = request.split_for(image.id)
            splits_seen.add(split)

            # Ultralytics finds labels by PATH CONVENTION, not configuration: it
            # takes the image path and swaps "/images/" for "/labels/", keeping
            # the same stem. This layout is mandatory, not stylistic — get it
            # wrong and training silently runs on zero labels.
            #
            #   images/train/foo.jpg  ->  labels/train/foo.txt
            img_dir = root / "images" / split
            lbl_dir = root / "labels" / split
            img_dir.mkdir(parents=True, exist_ok=True)
            lbl_dir.mkdir(parents=True, exist_ok=True)

            stem = Path(image.original_filename).stem

            query = select(Annotation).where(Annotation.image_id == image.id)
            if not request.include_unreviewed:
                query = query.where(Annotation.reviewed.is_(True))

            lines: list[str] = []
            for ann in db.scalars(query).all():
                cx, cy, nw, nh = coco_to_yolo(
                    ann.x, ann.y, ann.width, ann.height, image.width, image.height
                )
                idx = class_index[ann.category_id]
                # 6dp is the ultralytics convention: at 4K a single unit of the
                # 6th decimal is well under a pixel, so it is lossless in
                # practice while keeping files small.
                lines.append(f"{idx} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

            # Always write the .txt, even when empty. An image with no objects is
            # a legitimate NEGATIVE example and ultralytics uses it as such — a
            # missing file means "unlabelled", which is a different thing and
            # gets counted as a missing-label warning instead of training signal.
            (lbl_dir / f"{stem}.txt").write_text("\n".join(lines), encoding="utf-8")

            if request.copy_images:
                src = storage.project_dir(image.project_id) / image.filename
                if src.exists():
                    shutil.copy2(src, img_dir / image.original_filename)

        # data.yaml. Hand-written rather than via PyYAML: it's five lines, and
        # this avoids adding a dependency purely to emit a trivial file.
        #
        # NOTE: `path:` is deliberately OMITTED, not set to `root`.
        #
        # We build exports in a temp directory that is deleted as soon as the
        # download finishes, so writing an absolute `path:` bakes in a directory
        # that provably does not exist by the time anyone opens the zip.
        # Ultralytics resolves the dataset root as:
        #
        #     data.get("path") or Path(data["yaml_file"]).parent
        #
        # so omitting the key makes it use the data.yaml's OWN directory — which
        # is exactly right, and makes the zip portable to wherever it's
        # unpacked. Setting a *relative* path would not work either: ultralytics
        # resolves relative paths against its global DATASETS_DIR setting, not
        # against the yaml.
        names = "\n".join(f"  {i}: {c.name}" for i, c in enumerate(categories))
        yaml_lines = [
            "# Generated by CV Platform",
            "# 'path' intentionally omitted so ultralytics resolves the dataset",
            "# root to this file's own directory, making this export portable.",
            "train: images/train",
        ]
        # Only declare val if a val split actually exists — pointing at an empty
        # directory makes ultralytics fail with a confusing "no images found".
        if "val" in splits_seen:
            yaml_lines.append("val: images/val")
        else:
            yaml_lines.append("val: images/train  # no val split defined")
        yaml_lines += ["", f"nc: {len(categories)}", "names:", names, ""]

        (root / "data.yaml").write_text("\n".join(yaml_lines), encoding="utf-8")
        return root
