"""
Alembic environment — wired to the app's own engine and metadata.

Two deliberate choices:

- The DB URL comes from app.config.settings (via the app's engine), never from
  alembic.ini — one place authors where the database lives, and `alembic
  upgrade head` from the CLI operates on the same file the app uses.
- render_as_batch=True: SQLite cannot ALTER most things in place, so Alembic's
  batch mode (rebuild-table-and-copy) is what makes autogenerated migrations
  actually runnable here. Costless on other databases.
"""

from __future__ import annotations

import sys
from pathlib import Path

from alembic import context

# Runnable both by the app (init_db) and from the CLI in backend/ — either way
# the app package must be importable.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import Base, engine  # noqa: E402
from app import models  # noqa: F401, E402 — registers every model on Base.metadata

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """--sql mode: emit the SQL without a live connection."""
    context.configure(
        url=str(engine.url),
        target_metadata=target_metadata,
        literal_binds=True,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    # Tests migrate THROWAWAY databases by passing their own connection via
    # config.attributes — the documented Alembic seam for exactly this. The
    # app itself passes nothing and gets its own engine.
    supplied = context.config.attributes.get("connection")
    if supplied is not None:
        context.configure(
            connection=supplied,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()
        return

    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
